/**
 * GENERATED by scripts/tokens.mjs from design-system/tokens/tokens.json. Do not edit by hand.
 * Fixed brand values for JS and SVG consumers (inline gradients, SVG strokes, canvas).
 * Themed grounds (paper, surface, line) are NOT here: use Tailwind classes or rgb(var(--paper)).
 */

export const ROSE = { 50: '#FADEEE', 200: '#F3A0CC', 400: '#E85BA8' } as const;
export const APRICOT = { 50: '#FDECDF', 200: '#F8C39C', 400: '#F5A060' } as const;
export const LAVENDER = { 50: '#EDE1F7', 200: '#C9A3E6', 400: '#A668D9' } as const;
export const INK = { 100: '#F2EFEB', 200: '#E3DDD6', 400: '#A39B91', 500: '#6E665D', 600: '#5A534B', 900: '#1F1F1F' } as const;
export const SUCCESS = { 100: '#E2F5EC', 300: '#9AD3BC', 600: '#1F9D6B' } as const;
export const WARNING = { 100: '#FBF2DC', 300: '#E3C896', 600: '#C08415' } as const;
export const ERROR = { 100: '#FAE4E2', 300: '#E6A5A1', 600: '#C8382F' } as const;
export const CARBON = '#1F1F1F';
export const WHITE = '#FFFFFF';
export const PAPER_IVORY = '#F9F6F2';

/** Headline limits: every H1 has one accent word and between tilesMin and tilesMax picture tiles. */
export const HEADLINE = { tilesMin: 1, tilesMax: 3 } as const;

/** Banner loop limits in seconds: a banner drifts, it never races. */
export const BANNER = { speedMin: 32, speedMax: 60 } as const;

/** Floating tiles around the home headline: float in px, degrees and seconds; repel radius and force in px; spring settings. */
export const ICON_FLOAT = { rise: 8, drift: 6, turn: 5, durationMin: 5, durationMax: 10, repelRadius: 150, repelForce: 50, stiffness: 300, damping: 20 } as const;

/** Icon tile grounds as gradient stops ([colour, offset 0 to 1]), for baking a tile on a canvas. Light grounds add a hairline edge and a contact shadow colour. */
export const ICON_GROUNDS = { carbon: [['#36322F', 0], ['#2C2927', 0.55], ['#252220', 1]], paper: [['#FDFBF8', 0], ['#F9F6F2', 0.55], ['#F1ECE4', 1]], white: [['#FFFFFF', 0]], edgeLight: 'rgba(31, 31, 31, 0.08)', shadowLight: 'rgba(31, 31, 31, 0.14)' } as const;

/** The floating video: it docks once less than `threshold` of its space is visible. */
export const VIDEO_PIP = { threshold: 0.25, z: 40 } as const;

/** Content that plays on its own: how long one step holds, in ms. */
export const AUTOPLAY = { step: 6000 } as const;

/** Confetti: brand colours at 400 and 200, piece count, duration in ms and how high it pops. */
export const CELEBRATION = { colours: ['#F5A060', '#E85BA8', '#A668D9', '#F8C39C', '#F3A0CC', '#C9A3E6'], pieces: 30, duration: 1800, rise: '7rem' } as const;

/** The signature gradient stops, apricot to rose to lavender. Never reversed. */
export const GRADIENT_STOPS = [APRICOT[400], ROSE[400], LAVENDER[400]] as const;

/** The three gradients as CSS values, for inline-style consumers. */
export const BRAND_GRADIENT = 'linear-gradient(135deg, #F5A060 0%, #E85BA8 50%, #A668D9 100%)';
export const BRAND_GRADIENT_SOFT = 'linear-gradient(135deg, #FDECDF 0%, #FADEEE 50%, #EDE1F7 100%)';
export const BRAND_GRADIENT_DAWN = 'linear-gradient(160deg, #FFFFFF 0%, #FDECDF 55%, #FADEEE 100%)';
