/**
 * GENERATED by scripts/tokens.mjs from design-system/tokens/tokens.json. Do not edit by hand.
 * Tailwind preset: every Health OS class comes from here.
 *
 *   // tailwind.config.js
 *   import healthos from './design-system/tokens/tailwind.preset.js';
 *   export default { presets: [healthos], content: ['./index.html', './src/**\/*.{ts,tsx}'] };
 */
export default {
  "theme": {
    "colors": {
      "transparent": "transparent",
      "current": "currentColor",
      "white": "#FFFFFF",
      "carbon": "#1F1F1F",
      "rose": {
        "50": "#FADEEE",
        "400": "#E85BA8",
        "700": "#97215F"
      },
      "apricot": {
        "50": "#FDECDF",
        "400": "#F5A060",
        "700": "#9E5723"
      },
      "lavender": {
        "50": "#EDE1F7",
        "400": "#A666D9",
        "700": "#602C88"
      },
      "ink": {
        "100": "#F2EFEB",
        "200": "#E3DDD6",
        "400": "#A39B91",
        "500": "#7C746B",
        "600": "#5A534B",
        "900": "#1F1F1F"
      },
      "success": {
        "100": "#E2F5EC",
        "600": "#1F9D6B",
        "700": "#15724E"
      },
      "warning": {
        "100": "#FBF2DC",
        "600": "#C08415",
        "700": "#8A5E0F"
      },
      "error": {
        "100": "#FAE4E2",
        "600": "#C8382F",
        "700": "#9F2A23"
      },
      "paper": "rgb(var(--paper) / <alpha-value>)",
      "surface": "rgb(var(--surface) / <alpha-value>)",
      "surface-2": "rgb(var(--surface-2) / <alpha-value>)",
      "line": "rgb(var(--line) / <alpha-value>)",
      "line-soft": "rgb(var(--line-soft) / <alpha-value>)",
      "ground-textured": "rgb(var(--ground-textured) / <alpha-value>)"
    },
    "fontFamily": {
      "display": [
        "\"Spline Sans\"",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "\"Segoe UI\"",
        "sans-serif"
      ],
      "sans": [
        "\"Anonymous Pro\"",
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "monospace"
      ]
    },
    "fontSize": {
      "heading": [
        "clamp(2.25rem, 1.65rem + 2.25vw, 3.625rem)",
        {
          "lineHeight": "1.08",
          "letterSpacing": "-0.02em",
          "fontWeight": "700"
        }
      ],
      "subheading": [
        "clamp(1.25rem, 1.1rem + 0.5vw, 1.5rem)",
        {
          "lineHeight": "1.3",
          "letterSpacing": "-0.01em",
          "fontWeight": "600"
        }
      ],
      "body": [
        "1rem",
        {
          "lineHeight": "1.625",
          "letterSpacing": "0em",
          "fontWeight": "400"
        }
      ],
      "label": [
        "0.75rem",
        {
          "lineHeight": "1.34",
          "letterSpacing": "0.06em",
          "fontWeight": "700"
        }
      ]
    },
    "borderRadius": {
      "none": "0px",
      "md": "8px",
      "lg": "12px",
      "full": "9999px"
    },
    "boxShadow": {
      "none": "none",
      "sm": "0 1px 3px rgba(31, 31, 31, 0.06), 0 1px 2px rgba(31, 31, 31, 0.04)",
      "md": "0 4px 14px rgba(31, 31, 31, 0.06), 0 2px 4px rgba(31, 31, 31, 0.04)",
      "lg": "0 12px 32px rgba(31, 31, 31, 0.08), 0 4px 8px rgba(31, 31, 31, 0.04)"
    },
    "extend": {
      "spacing": {
        "hero-py": "7rem",
        "hero-py-lg": "11rem",
        "hero-gap": "3.5rem",
        "hero-gap-sm": "2rem"
      },
      "maxWidth": {
        "container": "1200px",
        "container-wide": "1320px",
        "reading": "680px",
        "hero-subcopy": "600px"
      },
      "transitionDuration": {
        "xs": "80ms",
        "sm": "160ms",
        "md": "240ms",
        "lg": "360ms",
        "xl": "480ms"
      },
      "transitionTimingFunction": {
        "out": "cubic-bezier(0.22, 1, 0.36, 1)",
        "standard": "cubic-bezier(0.4, 0, 0.2, 1)"
      },
      "backgroundImage": {
        "brand-gradient": "linear-gradient(135deg, #F5A060 0%, #E85BA8 50%, #A666D9 100%)",
        "brand-gradient-soft": "linear-gradient(135deg, #FDECDF 0%, #FADEEE 50%, #EDE1F7 100%)",
        "brand-gradient-warm": "linear-gradient(135deg, #FDECDF 0%, #F5A060 45%, #E85BA8 100%)"
      },
      "letterSpacing": {
        "label": "0.06em"
      },
      "keyframes": {
        "marquee": {
          "0%": {
            "transform": "translateX(0)"
          },
          "100%": {
            "transform": "translateX(-50%)"
          }
        },
        "marquee-reverse": {
          "0%": {
            "transform": "translateX(-50%)"
          },
          "100%": {
            "transform": "translateX(0)"
          }
        },
        "ticker": {
          "0%": {
            "transform": "translateX(0)"
          },
          "100%": {
            "transform": "translateX(-50%)"
          }
        },
        "shimmer": {
          "0%": {
            "backgroundPosition": "200% 0"
          },
          "100%": {
            "backgroundPosition": "-200% 0"
          }
        },
        "sheen": {
          "0%": {
            "WebkitMaskPosition": "100% 0",
            "maskPosition": "100% 0"
          },
          "100%": {
            "WebkitMaskPosition": "0% 0",
            "maskPosition": "0% 0"
          }
        },
        "enter-rise": {
          "from": {
            "opacity": "0",
            "transform": "translateY(4px)"
          },
          "to": {
            "opacity": "1",
            "transform": "translateY(0)"
          }
        }
      },
      "animation": {
        "marquee": "marquee 40s linear infinite",
        "marquee-slow": "marquee 60s linear infinite",
        "marquee-reverse": "marquee-reverse 40s linear infinite",
        "ticker": "ticker 32s linear infinite",
        "shimmer": "shimmer 6s linear infinite",
        "sheen": "sheen 2.4s linear infinite",
        "enter-rise": "enter-rise 240ms cubic-bezier(0.22, 1, 0.36, 1) both"
      }
    }
  }
};
