#!/usr/bin/env node
/**
 * docs.mjs — writes the reference documents from the same two files the site renders.
 *
 *   node scripts/docs.mjs          write design-system/REFERENCE.md, design-system/CHECKLIST.md, llms.txt
 *   node scripts/docs.mjs --check  exit 1 if any of them is out of date (used by `npm run build`)
 *
 * Sources: design-system/tokens/tokens.json (values) and design-system/reference/catalog.json
 * (purpose, when to use, when not to, API, source, checklist, open decisions). Edit those, never
 * the generated files, so the site and the written reference cannot disagree.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(ROOT, 'design-system/tokens/tokens.json'), 'utf8'));
const catalog = JSON.parse(readFileSync(join(ROOT, 'design-system/reference/catalog.json'), 'utf8'));

const SITE = 'https://ds-healthos.vercel.app';
const GENERATED = (sources) =>
  `> Generated by \`scripts/docs.mjs\` from ${sources}. Do not edit by hand: change the source and run \`npm run docs\`.`;

/* ── helpers ───────────────────────────────────────────────────────────── */
const entries = (group) => Object.entries(group).filter(([k]) => !k.startsWith('$'));
const val = (node) => node.$value;
const desc = (node) => node.$description ?? '';
/** Escape a table cell: pipes break GitHub tables, newlines break rows. */
const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
const code = (s) => `\`${String(s).replace(/`/g, "'")}\``;
const table = (head, rows) =>
  [`| ${head.join(' | ')} |`, `| ${head.map(() => '---').join(' | ')} |`, ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`)].join('\n');
const slug = (s) =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
const STATUS = { stable: 'Stable', experimental: 'Experimental', 'in-progress': 'In progress' };
const px = (rem) => `${parseFloat(rem) * 16}px`;

const sectionsIn = (group) => catalog.sections.filter((s) => s.group === group);
const entriesFor = (id) => catalog.entries.filter((e) => e.section === id);
const counts = {
  entries: catalog.entries.length,
  components: catalog.entries.filter((e) => e.kind === 'component').length,
  widgets: catalog.entries.filter((e) => e.kind === 'widget').length,
  patterns: catalog.entries.filter((e) => e.kind === 'pattern').length,
};

/* ── entry block ───────────────────────────────────────────────────────── */
function entryBlock(e, level = '###') {
  const title = e.number ? `${e.number} · ${e.name}` : e.name;
  const out = [`${level} ${title}`, ''];
  out.push(`${code(e.id)} · ${e.kind} · ${STATUS[e.status]}`, '');
  out.push(e.purpose, '');
  if (e.use.length) out.push('**Use it for**', '', ...e.use.map((u) => `- ${u}`), '');
  if (e.avoid.length) out.push('**Not for**', '', ...e.avoid.map((u) => `- ${u}`), '');
  out.push(`**API** ${code(e.api)}`, '', `**Source** ${code(e.source)}`, '');
  return out.join('\n');
}

/* ── token tables ──────────────────────────────────────────────────────── */
function tokenTables() {
  const out = [];
  const c = tokens.color;

  out.push('### Themes', '', desc(tokens.theme), '');
  out.push(
    table(
      ['Token', 'Class', 'Light', 'Paper', 'Role'],
      entries(tokens.theme.light).map(([k, n]) => [code(k), code(k.startsWith('line') ? `border-${k}` : `bg-${k}`), val(n), val(tokens.theme.paper[k]), desc(n)])
    ),
    ''
  );
  out.push('Light is the default. Paper is `.theme-paper` on `<html>`. Grounds are RGB channels: `rgb(var(--paper) / 0.5)`.', '');

  out.push('### Colour', '', desc(c), '');
  const rows = [];
  for (const hue of ['rose', 'apricot', 'lavender', 'ink', 'success', 'warning', 'error']) {
    for (const [step, n] of entries(c[hue])) rows.push([code(`${hue}-${step}`), val(n), code(`--hos-${hue}-${step}`), desc(n)]);
  }
  rows.push([code('carbon'), val(c.carbon), code('--hos-carbon'), desc(c.carbon)]);
  rows.push([code('white'), val(c.white), code('--hos-white'), desc(c.white)]);
  out.push(table(['Token', 'Hex', 'CSS variable', 'Role'], rows), '');
  out.push('Classes follow the token name: `bg-rose-50`, `text-rose-700`, `border-apricot-400`, `bg-carbon`.', '');

  out.push('### Gradients', '', desc(tokens.gradient), '');
  out.push(
    table(
      ['Class', 'CSS variable', 'Value', 'Role'],
      entries(tokens.gradient).map(([k, n]) => [code(`bg-${k}`), code(`--hos-${k}`), code(val(n)), desc(n)])
    ),
    ''
  );

  out.push('### Type', '', desc(tokens.font), '');
  out.push(
    table(
      ['Family', 'Class', 'Stack', 'Role'],
      entries(tokens.font.family).map(([k, n]) => [k, code(`font-${k}`), val(n).join(', '), desc(n)])
    ),
    ''
  );
  out.push(
    table(
      ['Role', 'Class', 'Family', 'Size', 'Line height', 'Tracking', 'Weight', 'Use'],
      entries(tokens.font.role).map(([k, n]) => {
        const v = val(n);
        return [k, code(`text-${k}`), code(`font-${v.fontFamily}`), code(v.fontSize), v.lineHeight, v.letterSpacing, v.fontWeight, desc(n)];
      })
    ),
    ''
  );
  out.push('Pair each role with its family: `font-display text-heading`, `font-display text-subheading`, `font-sans text-body`, `font-sans text-label`.', '');

  out.push('### Spacing', '', desc(tokens.space), '');
  out.push(
    table(
      ['Step', 'Value', 'Pixels', 'Class example', 'CSS variable', 'Use'],
      entries(tokens.space).map(([k, n]) => [code(k), val(n), px(val(n)), code(/^\d+$/.test(k) ? `p-${k}` : k.includes('gap') ? `mt-${k}` : `pt-${k}`), code(`--hos-space-${k}`), desc(n)])
    ),
    ''
  );

  out.push('### Radius', '', desc(tokens.radius), '');
  out.push(table(['Class', 'Value', 'Use'], entries(tokens.radius).map(([k, n]) => [code(`rounded-${k}`), val(n), desc(n)])), '');

  out.push('### Shadow', '', desc(tokens.shadow), '');
  out.push(table(['Class', 'Value', 'Use'], entries(tokens.shadow).map(([k, n]) => [code(`shadow-${k}`), code(val(n)), desc(n)])), '');

  out.push('### Sizes', '', desc(tokens.size), '');
  out.push(table(['Class', 'Value', 'Use'], entries(tokens.size).map(([k, n]) => [code(`max-w-${k}`), val(n), desc(n)])), '');

  out.push('### Motion', '', desc(tokens.motion), '');
  out.push(
    table(
      ['Class', 'Value', 'Use'],
      [
        ...entries(tokens.motion.duration).map(([k, n]) => [code(`duration-${k}`), val(n), desc(n)]),
        ...entries(tokens.motion.easing).map(([k, n]) => [code(`ease-${k}`), code(`cubic-bezier(${val(n).join(', ')})`), desc(n)]),
      ]
    ),
    ''
  );
  return out.join('\n');
}

/* ── REFERENCE.md ──────────────────────────────────────────────────────── */
function buildReference() {
  const out = [];
  out.push('# Health OS design system reference', '');
  out.push(GENERATED('`design-system/tokens/tokens.json` and `design-system/reference/catalog.json`'), '');
  out.push(
    `Every token, component, widget, pattern and asset library in the system, with what it is for, when to use it, when not to, its API and its source file. The reference site renders the same two files: ${SITE}`,
    ''
  );
  out.push(
    `Updated ${catalog.updated} · ${counts.entries} entries · ${counts.components} components · ${counts.widgets} widgets · ${counts.patterns} patterns · ${catalog.open.length} open decisions`,
    ''
  );

  out.push('## How to use this file', '');
  out.push(
    '- Take every value from the token tables. Tailwind classes come from `design-system/tokens/tailwind.preset.js`; CSS variables from `design-system/tokens/tokens.css`.',
    '- Pick components by their purpose, then check "Not for" before using one.',
    '- Stable means ready. Experimental means available and labelled, still being polished. In progress means not ready to use.',
    '- Run [CHECKLIST.md](CHECKLIST.md) before shipping anything.',
    '- Claims, prices, offers and voice come from the Health OS database (`teamos-ai/db-health-os`). This system never overrides them.',
    ''
  );

  out.push('## Contents', '');
  out.push('- [Open decisions](#open-decisions)');
  for (const group of catalog.groups.filter((g) => g !== 'Start')) {
    out.push(`- ${group}: ${sectionsIn(group).map((s) => `[${s.title}](#${slug(s.title)})`).join(' · ')}`);
  }
  out.push('');

  out.push('## Open decisions', '');
  out.push('Decisions still waiting on Tumai, and what the system does until each one is made.', '');
  out.push(table(['Topic', 'Ref', 'Question', 'For now'], catalog.open.map((o) => [o.topic, o.ref, o.question, o.current])), '');

  for (const group of catalog.groups.filter((g) => g !== 'Start')) {
    for (const s of sectionsIn(group)) {
      out.push(`## ${s.title}`, '');
      out.push(`${group}${s.lead ? ` · ${s.lead}` : ''}`, '');
      if (s.id === 'tokens') out.push(tokenTables());
      const es = entriesFor(s.id);
      if (s.id === 'widgets') {
        out.push(
          table(
            ['#', 'Widget', 'Group', 'Status', 'Inputs', 'Source'],
            es.map((e) => [e.number, e.name, e.group, STATUS[e.status], code(e.api), code(e.source)])
          ),
          ''
        );
        for (const g of [...new Set(es.map((e) => e.group))]) {
          out.push(`### ${g}`, '');
          for (const e of es.filter((x) => x.group === g)) out.push(entryBlock(e, '####'));
        }
      } else {
        for (const e of es) out.push(entryBlock(e));
      }
    }
  }
  return out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
}

/* ── CHECKLIST.md ──────────────────────────────────────────────────────── */
function buildChecklist() {
  const meta = catalog.sections.find((s) => s.id === 'checklist');
  return [
    `# ${meta.title}`,
    '',
    GENERATED('`design-system/reference/catalog.json`'),
    '',
    meta.lead,
    '',
    ...catalog.checklist.map((item, i) => `${i + 1}. ${item}`),
    '',
    'Exceptions follow the last item: a defined need the system cannot meet, written down, and approved by Tumai.',
    '',
    `The same list is interactive on the reference site: ${SITE}/#checklist`,
    '',
  ].join('\n');
}

/* ── llms.txt ──────────────────────────────────────────────────────────── */
function buildLlms() {
  const f = tokens.font.family;
  return [
    '# Health OS design system',
    '',
    `> The design and brand reference for Health OS, built for AI agents first and people second. Light and paper themes; ${val(f.display)[0]} headings and ${val(f.sans)[0]} body; rose, apricot and lavender in three shades each; three gradients; ${counts.components} components, six card types, ${counts.widgets} widgets and a tagged image library.`,
    '',
    'Read in this order. Take every value from the tokens and never type a hex, size, radius, shadow or duration by hand. Claims, prices, offers and voice come from the Health OS database (teamos-ai/db-health-os), which this system never overrides. Tumai approves every exception.',
    '',
    '## Start here',
    '',
    '- [CLAUDE.md](design-system/CLAUDE.md): the rules, the load order and how to change the system.',
    `- [CHECKLIST.md](design-system/CHECKLIST.md): the ${catalog.checklist.length} checks to run before shipping any page, post, email or asset.`,
    `- [REFERENCE.md](design-system/REFERENCE.md): every token table and all ${counts.entries} entries with purpose, when to use, when not to, API and source, plus the ${catalog.open.length} open decisions.`,
    '',
    '## Values',
    '',
    '- [tokens.json](design-system/tokens/tokens.json): the only source of token values, with a description on every token.',
    '- [tokens.css](design-system/tokens/tokens.css): generated CSS variables for any consumer, both themes.',
    '- [tailwind.preset.js](design-system/tokens/tailwind.preset.js): generated Tailwind preset. Off-system classes produce no CSS.',
    '',
    '## Brand, voice and recipes',
    '',
    '- [BRAND-SUMMARY.md](design-system/BRAND-SUMMARY.md): what Health OS is and how it should feel, in one page.',
    '- [VOICE.md](design-system/VOICE.md): how copy sits inside the system, and where the database takes over.',
    '- [ASSET-RECIPES.md](design-system/ASSET-RECIPES.md): which tokens and components to use for each kind of page or asset.',
    '- [logo/usage.md](design-system/logo/usage.md): the mark, its grounds and sizes.',
    '',
    '## Data',
    '',
    '- [catalog.json](design-system/reference/catalog.json): the catalogue behind the site and REFERENCE.md.',
    '- [photos.ts](src/data/photos.ts), [backgrounds.ts](src/data/backgrounds.ts), [media.ts](src/data/media.ts): the image library with context tags, tone, text space and one suggested use per image.',
    '- [offer.ts](src/data/offer.ts): plan names and AUD prices used in examples, copied from the database.',
    '',
    '## Optional',
    '',
    '- [README.md](README.md): the repository, commands and the build checks.',
    `- Reference site: ${SITE}`,
    '',
  ].join('\n');
}

/* ── write or check ────────────────────────────────────────────────────── */
const outputs = [
  ['design-system/REFERENCE.md', buildReference()],
  ['design-system/CHECKLIST.md', buildChecklist()],
  ['llms.txt', buildLlms()],
];

const check = process.argv.includes('--check');
let stale = 0;
for (const [rel, content] of outputs) {
  const file = join(ROOT, rel);
  const current = existsSync(file) ? readFileSync(file, 'utf8') : '';
  if (current === content) continue;
  if (check) {
    stale++;
    console.error(`✗ ${rel} is out of date. Run: npm run docs`);
  } else {
    writeFileSync(file, content);
    console.log(`✓ wrote ${rel}`);
  }
}
if (check && stale) process.exit(1);
if (check) console.log('✓ docs are in sync');
