#!/usr/bin/env node
/**
 * tokens.mjs — generates every token output from design-system/tokens/tokens.json.
 *
 *   node scripts/tokens.mjs          write tokens.css, tailwind.preset.js, src/lib/palette.ts
 *   node scripts/tokens.mjs --check  exit 1 if any generated file is out of date (used by `npm run build`)
 *
 * tokens.json is the only file a person edits. Everything below is derived, so the CSS
 * variables, the Tailwind classes and the JS palette can never disagree.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = join(ROOT, 'design-system/tokens/tokens.json');
const t = JSON.parse(readFileSync(SOURCE, 'utf8'));

const HEADER = (what) =>
  `GENERATED by scripts/tokens.mjs from design-system/tokens/tokens.json. Do not edit by hand.\n${what}`;

/* ── helpers ───────────────────────────────────────────────────────────── */
const entries = (group) => Object.entries(group).filter(([k]) => !k.startsWith('$'));
const val = (node) => node.$value;
const rgb = (hex) => {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(' ');
};
const ramps = ['rose', 'apricot', 'lavender', 'ink', 'success', 'warning', 'error'];
const themeKeys = entries(t.theme.light).map(([k]) => k);

/* ── tokens.css ────────────────────────────────────────────────────────── */
function buildCss() {
  const lines = [];
  lines.push('/**', ...HEADER('CSS custom properties for any consumer (React via Tailwind, widgets, embeds, email).').split('\n').map((l) => ` * ${l}`));
  lines.push(' *');
  lines.push(' * Themes: light is the default (no class). Paper is `.theme-paper` on <html>.');
  lines.push(' * Themed grounds are RGB channels so Tailwind can apply opacity: rgb(var(--paper) / 0.5).');
  lines.push(' */', '');

  const themeBlock = (selector, theme) => {
    lines.push(`${selector} {`);
    lines.push('  color-scheme: light;');
    for (const [key, node] of entries(theme)) {
      lines.push(`  --${key}: ${rgb(val(node))}; /* ${val(node)} ${node.$description ?? ''} */`);
    }
    lines.push('}', '');
  };
  themeBlock(':root', t.theme.light);
  themeBlock('.theme-paper', t.theme.paper);

  lines.push('/* Fixed values, identical in both themes. */');
  lines.push(':root {');
  for (const name of ramps) {
    for (const [step, node] of entries(t.color[name])) {
      lines.push(`  --hos-${name}-${step}: ${val(node)};`);
    }
  }
  lines.push(`  --hos-carbon: ${val(t.color.carbon)};`);
  lines.push(`  --hos-white: ${val(t.color.white)};`);
  for (const [name, node] of entries(t.gradient)) lines.push(`  --hos-${name}: ${val(node)};`);
  for (const [name, node] of entries(t.font.family)) {
    lines.push(`  --hos-font-${name}: ${val(node).map((f) => (f.includes(' ') ? `"${f}"` : f)).join(', ')};`);
  }
  for (const [name, node] of entries(t.space)) lines.push(`  --hos-space-${name}: ${val(node)};`);
  for (const [name, node] of entries(t.radius)) lines.push(`  --hos-radius-${name}: ${val(node)};`);
  for (const [name, node] of entries(t.shadow)) lines.push(`  --hos-shadow-${name}: ${val(node)};`);
  for (const [name, node] of entries(t.motion.duration)) lines.push(`  --hos-duration-${name}: ${val(node)};`);
  for (const [name, node] of entries(t.motion.easing)) lines.push(`  --hos-ease-${name}: cubic-bezier(${val(node).join(', ')});`);
  lines.push('}', '');
  return lines.join('\n');
}

/* ── tailwind.preset.js ────────────────────────────────────────────────── */
function buildPreset() {
  const colorObj = {
    transparent: 'transparent',
    current: 'currentColor',
    white: val(t.color.white),
    carbon: val(t.color.carbon),
  };
  for (const name of ramps) {
    colorObj[name] = Object.fromEntries(entries(t.color[name]).map(([s, n]) => [s, val(n)]));
  }
  for (const key of themeKeys) colorObj[key] = `rgb(var(--${key}) / <alpha-value>)`;

  const fontFamily = Object.fromEntries(entries(t.font.family).map(([k, n]) => [k, val(n).map((f) => (f.includes(' ') ? `"${f}"` : f))]));
  const fontSize = Object.fromEntries(
    entries(t.font.role).map(([k, n]) => {
      const v = val(n);
      return [k, [v.fontSize, { lineHeight: v.lineHeight, letterSpacing: v.letterSpacing, fontWeight: v.fontWeight }]];
    })
  );
  const borderRadius = Object.fromEntries(entries(t.radius).map(([k, n]) => [k, val(n)]));
  const boxShadow = { none: 'none', ...Object.fromEntries(entries(t.shadow).map(([k, n]) => [k, val(n)])) };
  // Numbered steps equal Tailwind's defaults, so only the named (hero) tokens are added.
  const spacing = Object.fromEntries(entries(t.space).filter(([k]) => !/^\d+$/.test(k)).map(([k, n]) => [k, val(n)]));
  const maxWidth = Object.fromEntries(entries(t.size).map(([k, n]) => [k, val(n)]));
  const transitionDuration = Object.fromEntries(entries(t.motion.duration).map(([k, n]) => [k, val(n)]));
  const transitionTimingFunction = Object.fromEntries(entries(t.motion.easing).map(([k, n]) => [k, `cubic-bezier(${val(n).join(', ')})`]));
  const backgroundImage = Object.fromEntries(entries(t.gradient).map(([k, n]) => [k, val(n)]));

  const preset = {
    theme: {
      // Overridden (not extended) so only system values exist: an off-system class
      // such as `text-5xl`, `rounded-xl` or `bg-violet-500` generates no CSS at all.
      colors: colorObj,
      fontFamily,
      fontSize,
      borderRadius,
      boxShadow,
      extend: {
        spacing,
        maxWidth,
        transitionDuration,
        transitionTimingFunction,
        backgroundImage,
        letterSpacing: { label: '0.06em' },
        keyframes: {
          marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
          'marquee-reverse': { '0%': { transform: 'translateX(-50%)' }, '100%': { transform: 'translateX(0)' } },
          ticker: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
          shimmer: { '0%': { backgroundPosition: '200% 0' }, '100%': { backgroundPosition: '-200% 0' } },
          sheen: { '0%': { WebkitMaskPosition: '100% 0', maskPosition: '100% 0' }, '100%': { WebkitMaskPosition: '0% 0', maskPosition: '0% 0' } },
          'enter-rise': { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        },
        animation: {
          marquee: 'marquee 40s linear infinite',
          'marquee-slow': 'marquee 60s linear infinite',
          'marquee-reverse': 'marquee-reverse 40s linear infinite',
          ticker: 'ticker 32s linear infinite',
          shimmer: 'shimmer 6s linear infinite',
          sheen: 'sheen 2.4s linear infinite',
          'enter-rise': `enter-rise ${val(t.motion.duration.md)} cubic-bezier(${val(t.motion.easing.out).join(', ')}) both`,
        },
      },
    },
  };

  return [
    '/**',
    ...HEADER('Tailwind preset: every Health OS class comes from here.').split('\n').map((l) => ` * ${l}`),
    ' *',
    " *   // tailwind.config.js",
    " *   import healthos from './design-system/tokens/tailwind.preset.js';",
    " *   export default { presets: [healthos], content: ['./index.html', './src/**\\/*.{ts,tsx}'] };",
    ' */',
    `export default ${JSON.stringify(preset, null, 2)};`,
    '',
  ].join('\n');
}

/* ── src/lib/palette.ts ────────────────────────────────────────────────── */
function buildPalette() {
  const c = t.color;
  const ramp = (name) =>
    `{ ${entries(c[name]).map(([s, n]) => `${s}: '${val(n)}'`).join(', ')} } as const`;
  return [
    '/**',
    ...HEADER('Fixed brand values for JS and SVG consumers (inline gradients, SVG strokes, canvas).').split('\n').map((l) => ` * ${l}`),
    ' * Themed grounds (paper, surface, line) are NOT here: use Tailwind classes or rgb(var(--paper)).',
    ' */',
    '',
    `export const ROSE = ${ramp('rose')};`,
    `export const APRICOT = ${ramp('apricot')};`,
    `export const LAVENDER = ${ramp('lavender')};`,
    `export const INK = ${ramp('ink')};`,
    `export const SUCCESS = ${ramp('success')};`,
    `export const WARNING = ${ramp('warning')};`,
    `export const ERROR = ${ramp('error')};`,
    `export const CARBON = '${val(c.carbon)}';`,
    `export const WHITE = '${val(c.white)}';`,
    `export const PAPER_IVORY = '${val(t.theme.paper.paper)}';`,
    '',
    '/** The signature gradient stops, apricot to rose to lavender. Never reversed. */',
    'export const GRADIENT_STOPS = [APRICOT[400], ROSE[400], LAVENDER[400]] as const;',
    '',
    '/** The three gradients as CSS values, for inline-style consumers. */',
    `export const BRAND_GRADIENT = '${val(t.gradient['brand-gradient'])}';`,
    `export const BRAND_GRADIENT_SOFT = '${val(t.gradient['brand-gradient-soft'])}';`,
    `export const BRAND_GRADIENT_WARM = '${val(t.gradient['brand-gradient-warm'])}';`,
    '',
  ].join('\n');
}

/* ── write or check ────────────────────────────────────────────────────── */
const outputs = [
  ['design-system/tokens/tokens.css', buildCss()],
  ['design-system/tokens/tailwind.preset.js', buildPreset()],
  ['src/lib/palette.ts', buildPalette()],
];

const check = process.argv.includes('--check');
let stale = 0;
for (const [rel, content] of outputs) {
  const file = join(ROOT, rel);
  const current = existsSync(file) ? readFileSync(file, 'utf8') : '';
  if (current === content) continue;
  if (check) {
    stale++;
    console.error(`✗ ${relative(ROOT, file)} is out of date. Run: npm run tokens`);
  } else {
    writeFileSync(file, content);
    console.log(`✓ wrote ${rel}`);
  }
}
if (check && stale) process.exit(1);
if (check) console.log('✓ tokens are in sync');
